language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t andreamontenegroem/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run andreamontenegroem/react-test npm test -- --coverage

after_success:
  - docker build -t andreamontenegroem/complex-client ./client
  - docker build -t andreamontenegroem/complex-nginx ./nginx
  - docker build -t andreamontenegroem/complex-server ./server
  - docker build -t andreamontenegroem/complex-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push andreamontenegroem/complex-client
  - docker push andreamontenegroem/complex-nginx
  - docker push andreamontenegroem/complex-server
  - docker push andreamontenegroem/complex-worker
